### ISSUE TITLE
URI ontology needs replace or is an error

### ISSUE THREAD

**Issue by mosoriob** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#10]
For example:
```
     @prefix j.3:   <http://www.opmw.org/ontology/> .
<http://www.opmw.org/export/resource/WorkflowExecutionArtifact/Caesar_Cypher-1f-f788bcd8-75d9-4996-974d-ef6a442a36da_EncryptedDocument>
        a                   j.3:WorkflowExecutionArtifact ;
```
Thus, the type of resource is:
http://www.opmw.org/ontology/WorkflowExecutionArtifact
However, http://www.opmw.org/model/OPMW/WorkflowExecutionArtifact doesn't exist.

http://www.opmw.org/model/OPMW#WorkflowExecutionArtifact exist. 

Do you except replace / to # or is an error?

**Comment by dgarijo** [comment]
The right URI is http://www.opmw.org/ontology/WorkflowExecutionArtifact.
Anything else is an error.

**Comment by mosoriob** [comment]
Ok, the redirect is already done.
