### ISSUE TITLE
domain is not properly exported

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#12]
In http://www.opmw.org/page/export/resource/WorkflowTemplate/ClimComp_Precipi-894eb652-60be-497e-974a-d64c5ffdad86_v1
It says 
 opmw:hasDomain ClimComp_Precipi-894eb652-60be-497e-974a-d64c5ffdad86.owl#
Which is not correct. The domain probably is "MINT-Production". 

Check whether this is an error in the mapper code or when doing the merging in WINGS.

**Comment by mosoriob** [comment]
![image](https://user-images.githubusercontent.com/2365990/59646105-62ec4b00-9143-11e9-9a9c-5f05d21b8159.png)
Fixed

**Comment by dgarijo** [comment]
Ah, I see you added it as a parameter. +1!
