### ISSUE TITLE
Issue related with hasMainScript

### ISSUE THREAD

**Issue by mosoriob** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#16]
- [ ] The config has a node blank
https://www.opmw.org/page/export/resource/SoftwareConfiguration/SingleProteomicS-7eca5052-f1de-4ef5-a0b8-b383fa805293_myrimatchNode_config

- [ ] The ontology does not have information about the property https://www.opmw.org/model/OPMW/#hasMainScript

**Comment by dgarijo** [comment]
Regarding the missing property:
In the latest version of the mapper, I have introduced a series of updates, which are not reflected in the main ontology yet. Some of these have to be aligned to the recent Software Description Ontology

**Comment by mosoriob** [comment]
Fixed. However, we need to align OPMW with the ontology
