### ISSUE TITLE
Abstract template is not exported

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#18]
**Describe the bug**
When the template exported is concrete, the abstract template does not seem to be exported correctly. 

**To Reproduce**
See https://www.opmw.org/export/resource/WorkflowTemplate/ClimComp_Precipitation_v1

**Expected behavior**
There should be a template in the above URL. Instead there is nothing.

**Comment by mosoriob** [comment]
Done
