### ISSUE TITLE
Domain is exported incorrectly

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#19]
**Describe the bug**
The domain for https://www.opmw.org/export/resource/WorkflowTemplate/cycles_v2_standa-a1eac1b5-3eb5-4d86-9fe5-f13b28e0f9e1_v1 should not be cycles_v2_standa-a1eac1b5-3eb5-4d86-9fe5-f13b28e0f9e1.owl#

**To Reproduce**
Go to https://www.opmw.org/export/resource/WorkflowTemplate/cycles_v2_standa-a1eac1b5-3eb5-4d86-9fe5-f13b28e0f9e1_v1 and check property hasDomain

**Expected behavior**
The domain should be "mint". There is a wrong assumption on where to extract it from the URL of the template. It should be a parameter.

**Comment by mosoriob** [comment]
![image](https://user-images.githubusercontent.com/2365990/59646111-6d0e4980-9143-11e9-8dda-9f7c6e827f9f.png)
Fixed
