### ISSUE TITLE
Add proper prefixes to RDF explorer

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#20]
**Describe the bug**
Prefixes are super confusing

**To Reproduce**
N/A

**Expected behavior**
https://www.opmw.org/ontology/WorkflowTemplateProcess should be opmw:WorkflowTemplateProcess.

wings:export/MINT-production/Component#cycles_v2Class_V1 should be mint:cycles_v2Class_V1

etc.

**Comment by mosoriob** [comment]
And  https://w3id.org/wings/export/MINT-production/resource/CanonicalInstance/cycles_v2_V1?

**Comment by mosoriob** [comment]
Done
