### ISSUE TITLE
Redirect domain types; publish types

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#21]
**Describe the bug**
https://w3id.org/wings/export/MINT-production/Component#cycles_v2Class_V1 leads to a 404. It should be redirected to where the file is published. But I don't know where is it published yet! This is the "domain" file @sirspock. Is it published anywhere? 

**To Reproduce**
N/A

**Expected behavior**
https://w3id.org/wings/export/MINT-production/Component#cycles_v2Class_V1 should redirect to the description file

**Comment by mosoriob** [comment]
Done https://rdfexplorer.mint.isi.edu/data/wings/export/Domain/MINT-production#cycles_v2Class_V1
