### ISSUE TITLE
OPMW redirection does not work correctly

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#24]
**Describe the bug**
There is a problem with the ontology ns redirection.
https://www.opmw.org/ontology/executionStatus works, but 
https://www.opmw.org/ontology/ does not work (404), and neither does 
https://www.opmw.org/ontology

**To Reproduce**
N/A

**Expected behavior**
The redirection of the ontology should work. @sirspock where is the htaccess?

**Comment by mosoriob** [comment]
Done
