### ISSUE TITLE
Upload the domains file to the triple store too

### ISSUE THREAD

**Issue by dgarijo** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#7]
In another graph. This will facilitate querying

**Comment by mosoriob** [comment]
The url will be: w3id.org/[dataset]/Domain/[domainName]

**Comment by mosoriob** [comment]
@dgarijo We need the username in the URL because multiple users can have domains with the same name. I propose w3id.org/[dataset]/Domain/[username]_[domainName]

**Comment by dgarijo** [comment]
No, no!
The whole purpose of the mapper effort is to have a shared space for publishing workflows. If 2 users have the same domain in the same WINGS instance, the mapper will take care of it and do proper versioning. If one extends a workflow from another user, it will be taken care of.

The only problem I see is if 2 WINGS instances have domain files which are not synchronized, but even in that case it should be fine because the md5 hashes should take it into account. Please keep w3id.org/[dataset]/Domain/[domainName] .
