### ISSUE TITLE
w3id wings

### ISSUE THREAD

**Issue by mosoriob** [tirthmehta/WINGS_WORKFLOW_PROVENANCE_SCENARIOS#9]
Is this URI correct? Is it deprecated? 
https://w3id.org/wings/export/CaesarCypher/extension#uses_as_Param1key

**Comment by dgarijo** [comment]
No, this one we need to add the right redirect. We need to discuss a
methodology. And the pending conversation is the link back to
ontosoft/model catalog.

**Comment by dgarijo** [comment]
The URI is correct
